In [136]:
import pandas as pd

In [137]:
## load the movies data into a panda dataframe
df = pd.read_csv('movies.csv')

In [138]:
df

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
0,Adventure Squirrels,2/15/2016,Color,Drama,French,France,G,Jim Tickle,Lloyd Christmas,314.0,798.0,25.0,1310.0,6.7,54.0,93.0,1200000.0,100000.0
1,Too Many Balloons,9/15/2016,Color,Crime,English,USA,R,Phil Stump,Alan Creamsicle,309.0,520.0,26.0,10805.0,4.2,192.0,110.0,3000000.0,280000.0
2,That's Not Cheese,1/26/2016,B&W,Drama,German,Germany,Not Rated,Justin Groove,Anne Spandex,291.0,938.0,12.0,11501.0,8.3,215.0,145.0,3450000.0,650000.0
3,Sugar Rush,11/11/2016,Color,Comedy,English,USA,PG,Karen Trout,Humberto Guava,431.0,673.0,22.0,18363.0,6.3,433.0,100.0,2808000.0,379000.0
4,Why is Grandma Laughing?,8/29/2016,Color,Mystery,English,USA,PG-13,Yulia Velasquez,Purd Haply,86.0,623.0,1.0,4771.0,7.7,110.0,89.0,1700000.0,439000.0
5,Luke Warm Soup,4/15/2016,Color,Horror,English,USA,R,Skeeter McGavin,Nick Winkle,167.0,659.0,20.0,14580.0,9.3,209.0,81.0,3000000.0,609000.0
6,Clown Parade III,6/1/2016,Color,Comedy,English,USA,PG,Stan Pancake,Todd Waffle,444.0,900.0,11.0,15977.0,4.2,172.0,112.0,3250000.0,500000.0
7,Gene's Genes,8/11/2016,Color,Sci-Fi,Spanish,Spain,PG,Randy Killnose,August Clementine,406.0,879.0,6.0,10949.0,6.6,123.0,121.0,1980000.0,250000.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [139]:
df.drop(8,)

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
0,Adventure Squirrels,2/15/2016,Color,Drama,French,France,G,Jim Tickle,Lloyd Christmas,314.0,798.0,25.0,1310.0,6.7,54.0,93.0,1200000.0,100000.0
1,Too Many Balloons,9/15/2016,Color,Crime,English,USA,R,Phil Stump,Alan Creamsicle,309.0,520.0,26.0,10805.0,4.2,192.0,110.0,3000000.0,280000.0
2,That's Not Cheese,1/26/2016,B&W,Drama,German,Germany,Not Rated,Justin Groove,Anne Spandex,291.0,938.0,12.0,11501.0,8.3,215.0,145.0,3450000.0,650000.0
3,Sugar Rush,11/11/2016,Color,Comedy,English,USA,PG,Karen Trout,Humberto Guava,431.0,673.0,22.0,18363.0,6.3,433.0,100.0,2808000.0,379000.0
4,Why is Grandma Laughing?,8/29/2016,Color,Mystery,English,USA,PG-13,Yulia Velasquez,Purd Haply,86.0,623.0,1.0,4771.0,7.7,110.0,89.0,1700000.0,439000.0
5,Luke Warm Soup,4/15/2016,Color,Horror,English,USA,R,Skeeter McGavin,Nick Winkle,167.0,659.0,20.0,14580.0,9.3,209.0,81.0,3000000.0,609000.0
6,Clown Parade III,6/1/2016,Color,Comedy,English,USA,PG,Stan Pancake,Todd Waffle,444.0,900.0,11.0,15977.0,4.2,172.0,112.0,3250000.0,500000.0
7,Gene's Genes,8/11/2016,Color,Sci-Fi,Spanish,Spain,PG,Randy Killnose,August Clementine,406.0,879.0,6.0,10949.0,6.6,123.0,121.0,1980000.0,250000.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [140]:
df.drop(9)

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
0,Adventure Squirrels,2/15/2016,Color,Drama,French,France,G,Jim Tickle,Lloyd Christmas,314.0,798.0,25.0,1310.0,6.7,54.0,93.0,1200000.0,100000.0
1,Too Many Balloons,9/15/2016,Color,Crime,English,USA,R,Phil Stump,Alan Creamsicle,309.0,520.0,26.0,10805.0,4.2,192.0,110.0,3000000.0,280000.0
2,That's Not Cheese,1/26/2016,B&W,Drama,German,Germany,Not Rated,Justin Groove,Anne Spandex,291.0,938.0,12.0,11501.0,8.3,215.0,145.0,3450000.0,650000.0
3,Sugar Rush,11/11/2016,Color,Comedy,English,USA,PG,Karen Trout,Humberto Guava,431.0,673.0,22.0,18363.0,6.3,433.0,100.0,2808000.0,379000.0
4,Why is Grandma Laughing?,8/29/2016,Color,Mystery,English,USA,PG-13,Yulia Velasquez,Purd Haply,86.0,623.0,1.0,4771.0,7.7,110.0,89.0,1700000.0,439000.0
5,Luke Warm Soup,4/15/2016,Color,Horror,English,USA,R,Skeeter McGavin,Nick Winkle,167.0,659.0,20.0,14580.0,9.3,209.0,81.0,3000000.0,609000.0
6,Clown Parade III,6/1/2016,Color,Comedy,English,USA,PG,Stan Pancake,Todd Waffle,444.0,900.0,11.0,15977.0,4.2,172.0,112.0,3250000.0,500000.0
7,Gene's Genes,8/11/2016,Color,Sci-Fi,Spanish,Spain,PG,Randy Killnose,August Clementine,406.0,879.0,6.0,10949.0,6.6,123.0,121.0,1980000.0,250000.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [141]:
df.drop(10, inplace = True)

In [142]:
df

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
0,Adventure Squirrels,2/15/2016,Color,Drama,French,France,G,Jim Tickle,Lloyd Christmas,314.0,798.0,25.0,1310.0,6.7,54.0,93.0,1200000.0,100000.0
1,Too Many Balloons,9/15/2016,Color,Crime,English,USA,R,Phil Stump,Alan Creamsicle,309.0,520.0,26.0,10805.0,4.2,192.0,110.0,3000000.0,280000.0
2,That's Not Cheese,1/26/2016,B&W,Drama,German,Germany,Not Rated,Justin Groove,Anne Spandex,291.0,938.0,12.0,11501.0,8.3,215.0,145.0,3450000.0,650000.0
3,Sugar Rush,11/11/2016,Color,Comedy,English,USA,PG,Karen Trout,Humberto Guava,431.0,673.0,22.0,18363.0,6.3,433.0,100.0,2808000.0,379000.0
4,Why is Grandma Laughing?,8/29/2016,Color,Mystery,English,USA,PG-13,Yulia Velasquez,Purd Haply,86.0,623.0,1.0,4771.0,7.7,110.0,89.0,1700000.0,439000.0
5,Luke Warm Soup,4/15/2016,Color,Horror,English,USA,R,Skeeter McGavin,Nick Winkle,167.0,659.0,20.0,14580.0,9.3,209.0,81.0,3000000.0,609000.0
6,Clown Parade III,6/1/2016,Color,Comedy,English,USA,PG,Stan Pancake,Todd Waffle,444.0,900.0,11.0,15977.0,4.2,172.0,112.0,3250000.0,500000.0
7,Gene's Genes,8/11/2016,Color,Sci-Fi,Spanish,Spain,PG,Randy Killnose,August Clementine,406.0,879.0,6.0,10949.0,6.6,123.0,121.0,1980000.0,250000.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [143]:
df.drop(8,  inplace = True)

In [144]:
df.drop(9, inplace = True)

In [145]:
df

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
0,Adventure Squirrels,2/15/2016,Color,Drama,French,France,G,Jim Tickle,Lloyd Christmas,314.0,798.0,25.0,1310.0,6.7,54.0,93.0,1200000.0,100000.0
1,Too Many Balloons,9/15/2016,Color,Crime,English,USA,R,Phil Stump,Alan Creamsicle,309.0,520.0,26.0,10805.0,4.2,192.0,110.0,3000000.0,280000.0
2,That's Not Cheese,1/26/2016,B&W,Drama,German,Germany,Not Rated,Justin Groove,Anne Spandex,291.0,938.0,12.0,11501.0,8.3,215.0,145.0,3450000.0,650000.0
3,Sugar Rush,11/11/2016,Color,Comedy,English,USA,PG,Karen Trout,Humberto Guava,431.0,673.0,22.0,18363.0,6.3,433.0,100.0,2808000.0,379000.0
4,Why is Grandma Laughing?,8/29/2016,Color,Mystery,English,USA,PG-13,Yulia Velasquez,Purd Haply,86.0,623.0,1.0,4771.0,7.7,110.0,89.0,1700000.0,439000.0
5,Luke Warm Soup,4/15/2016,Color,Horror,English,USA,R,Skeeter McGavin,Nick Winkle,167.0,659.0,20.0,14580.0,9.3,209.0,81.0,3000000.0,609000.0
6,Clown Parade III,6/1/2016,Color,Comedy,English,USA,PG,Stan Pancake,Todd Waffle,444.0,900.0,11.0,15977.0,4.2,172.0,112.0,3250000.0,500000.0
7,Gene's Genes,8/11/2016,Color,Sci-Fi,Spanish,Spain,PG,Randy Killnose,August Clementine,406.0,879.0,6.0,10949.0,6.6,123.0,121.0,1980000.0,250000.0

In [151]:
# fetch all movies rated PG-13
h =df['Rating'] == 'PG-13'
df[h]

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
4,Why is Grandma Laughing?,8/29/2016,Color,Mystery,English,USA,PG-13,Yulia Velasquez,Purd Haply,86.0,623.0,1.0,4771.0,7.7,110.0,89.0,1700000.0,439000.0

In [158]:
# FETCH ALL NOT RATED MOVIES WITH AN IMDB SCORE ABOVE 6.
k= df['Rating'] == 'Not Rated'
n = df['IMDb Score (1-10)'] > 6.0
df[k|n]

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
0,Adventure Squirrels,2/15/2016,Color,Drama,French,France,G,Jim Tickle,Lloyd Christmas,314.0,798.0,25.0,1310.0,6.7,54.0,93.0,1200000.0,100000.0
2,That's Not Cheese,1/26/2016,B&W,Drama,German,Germany,Not Rated,Justin Groove,Anne Spandex,291.0,938.0,12.0,11501.0,8.3,215.0,145.0,3450000.0,650000.0
3,Sugar Rush,11/11/2016,Color,Comedy,English,USA,PG,Karen Trout,Humberto Guava,431.0,673.0,22.0,18363.0,6.3,433.0,100.0,2808000.0,379000.0
4,Why is Grandma Laughing?,8/29/2016,Color,Mystery,English,USA,PG-13,Yulia Velasquez,Purd Haply,86.0,623.0,1.0,4771.0,7.7,110.0,89.0,1700000.0,439000.0
5,Luke Warm Soup,4/15/2016,Color,Horror,English,USA,R,Skeeter McGavin,Nick Winkle,167.0,659.0,20.0,14580.0,9.3,209.0,81.0,3000000.0,609000.0
7,Gene's Genes,8/11/2016,Color,Sci-Fi,Spanish,Spain,PG,Randy Killnose,August Clementine,406.0,879.0,6.0,10949.0,6.6,123.0,121.0,1980000.0,250000.0

In [50]:
# RATING
g = df['Rating'] == 'G'
df[g]

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
0,Adventure Squirrels,2/15/2016,Color,Drama,French,France,G,Jim Tickle,Lloyd Christmas,314.0,798.0,25.0,1310.0,6.7,54.0,93.0,1200000.0,100000.0

In [52]:
# FETCH ALL G-RATED MOVIES WITH GROSS REVENUE ABOVE $1,000,000
r = df['Gross Revenue'] > 1000000.0
df[r]

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
0,Adventure Squirrels,2/15/2016,Color,Drama,French,France,G,Jim Tickle,Lloyd Christmas,314.0,798.0,25.0,1310.0,6.7,54.0,93.0,1200000.0,100000.0
1,Too Many Balloons,9/15/2016,Color,Crime,English,USA,R,Phil Stump,Alan Creamsicle,309.0,520.0,26.0,10805.0,4.2,192.0,110.0,3000000.0,280000.0
2,That's Not Cheese,1/26/2016,B&W,Drama,German,Germany,Not Rated,Justin Groove,Anne Spandex,291.0,938.0,12.0,11501.0,8.3,215.0,145.0,3450000.0,650000.0
3,Sugar Rush,11/11/2016,Color,Comedy,English,USA,PG,Karen Trout,Humberto Guava,431.0,673.0,22.0,18363.0,6.3,433.0,100.0,2808000.0,379000.0
4,Why is Grandma Laughing?,8/29/2016,Color,Mystery,English,USA,PG-13,Yulia Velasquez,Purd Haply,86.0,623.0,1.0,4771.0,7.7,110.0,89.0,1700000.0,439000.0
5,Luke Warm Soup,4/15/2016,Color,Horror,English,USA,R,Skeeter McGavin,Nick Winkle,167.0,659.0,20.0,14580.0,9.3,209.0,81.0,3000000.0,609000.0
6,Clown Parade III,6/1/2016,Color,Comedy,English,USA,PG,Stan Pancake,Todd Waffle,444.0,900.0,11.0,15977.0,4.2,172.0,112.0,3250000.0,500000.0
7,Gene's Genes,8/11/2016,Color,Sci-Fi,Spanish,Spain,PG,Randy Killnose,August Clementine,406.0,879.0,6.0,10949.0,6.6,123.0,121.0,1980000.0,250000.0

In [54]:
# SCORE AND REVIEW FETCH
df[g * r]

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
0,Adventure Squirrels,2/15/2016,Color,Drama,French,France,G,Jim Tickle,Lloyd Christmas,314.0,798.0,25.0,1310.0,6.7,54.0,93.0,1200000.0,100000.0

In [57]:
# FETCH ALL MOVIES WITH AN IMDB SCORE OF 8.0 HIGHER.
x = df['IMDb Score (1-10)'] >= 8.0
df[x]

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
2,That's Not Cheese,1/26/2016,B&W,Drama,German,Germany,Not Rated,Justin Groove,Anne Spandex,291.0,938.0,12.0,11501.0,8.3,215.0,145.0,3450000.0,650000.0
5,Luke Warm Soup,4/15/2016,Color,Horror,English,USA,R,Skeeter McGavin,Nick Winkle,167.0,659.0,20.0,14580.0,9.3,209.0,81.0,3000000.0,609000.0

In [59]:
## FETCH ALL MOVIES WITH TOTAL REVIEWS GREATER THAN 200
u = df['Total Reviews'] > 200.0
df[u]

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
2,That's Not Cheese,1/26/2016,B&W,Drama,German,Germany,Not Rated,Justin Groove,Anne Spandex,291.0,938.0,12.0,11501.0,8.3,215.0,145.0,3450000.0,650000.0
3,Sugar Rush,11/11/2016,Color,Comedy,English,USA,PG,Karen Trout,Humberto Guava,431.0,673.0,22.0,18363.0,6.3,433.0,100.0,2808000.0,379000.0
5,Luke Warm Soup,4/15/2016,Color,Horror,English,USA,R,Skeeter McGavin,Nick Winkle,167.0,659.0,20.0,14580.0,9.3,209.0,81.0,3000000.0,609000.0

In [162]:
## fetch all movies with an imdb score below
v = df['IMDb Score (1-10)'] < 5.0
df[v][['Genre', 'Director Name']]

    Genre    Director Name
1   Crime  Alan Creamsicle
6  Comedy      Todd Waffle

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
1,Too Many Balloons,9/15/2016,Color,Crime,English,USA,R,Phil Stump,Alan Creamsicle,309.0,520.0,26.0,10805.0,4.2,192.0,110.0,3000000.0,280000.0
6,Clown Parade III,6/1/2016,Color,Comedy,English,USA,PG,Stan Pancake,Todd Waffle,444.0,900.0,11.0,15977.0,4.2,172.0,112.0,3250000.0,500000.0

In [153]:
# FETCH ALL MOVIES WHERE THE LEAD ACTOR IS KAREN TROUT
y = df['Lead Actor'] == 'Karen Trout'
df[y]

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
3,Sugar Rush,11/11/2016,Color,Comedy,English,USA,PG,Karen Trout,Humberto Guava,431.0,673.0,22.0,18363.0,6.3,433.0,100.0,2808000.0,379000.0

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
0,Adventure Squirrels,2/15/2016,Color,Drama,French,France,G,Jim Tickle,Lloyd Christmas,314.0,798.0,25.0,1310.0,6.7,54.0,93.0,1200000.0,100000.0
1,Too Many Balloons,9/15/2016,Color,Crime,English,USA,R,Phil Stump,Alan Creamsicle,309.0,520.0,26.0,10805.0,4.2,192.0,110.0,3000000.0,280000.0
2,That's Not Cheese,1/26/2016,B&W,Drama,German,Germany,Not Rated,Justin Groove,Anne Spandex,291.0,938.0,12.0,11501.0,8.3,215.0,145.0,3450000.0,650000.0
3,Sugar Rush,11/11/2016,Color,Comedy,English,USA,PG,Karen Trout,Humberto Guava,431.0,673.0,22.0,18363.0,6.3,433.0,100.0,2808000.0,379000.0
4,Why is Grandma Laughing?,8/29/2016,Color,Mystery,English,USA,PG-13,Yulia Velasquez,Purd Haply,86.0,623.0,1.0,4771.0,7.7,110.0,89.0,1700000.0,439000.0
5,Luke Warm Soup,4/15/2016,Color,Horror,English,USA,R,Skeeter McGavin,Nick Winkle,167.0,659.0,20.0,14580.0,9.3,209.0,81.0,3000000.0,609000.0
6,Clown Parade III,6/1/2016,Color,Comedy,English,USA,PG,Stan Pancake,Todd Waffle,444.0,900.0,11.0,15977.0,4.2,172.0,112.0,3250000.0,500000.0
7,Gene's Genes,8/11/2016,Color,Sci-Fi,Spanish,Spain,PG,Randy Killnose,August Clementine,406.0,879.0,6.0,10949.0,6.6,123.0,121.0,1980000.0,250000.0

In [107]:
# FETCH ALL MOVIES DIRECTOR BY TODD WAFFLE.
df[df['Director Name'] == 'Todd Waffle']

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
6,Clown Parade III,6/1/2016,Color,Comedy,English,USA,PG,Stan Pancake,Todd Waffle,444.0,900.0,11.0,15977.0,4.2,172.0,112.0,3250000.0,500000.0

In [120]:
# FETCH ALL MOVIES WHERE THE LEAD ACTOR FB LIKE IS HIGHER THEN DIRECTOR FB LIKES.
u = df['Lead Actor FB Likes'] 
b = df['Director FB Likes']
df[u > b]

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
0,Adventure Squirrels,2/15/2016,Color,Drama,French,France,G,Jim Tickle,Lloyd Christmas,314.0,798.0,25.0,1310.0,6.7,54.0,93.0,1200000.0,100000.0
1,Too Many Balloons,9/15/2016,Color,Crime,English,USA,R,Phil Stump,Alan Creamsicle,309.0,520.0,26.0,10805.0,4.2,192.0,110.0,3000000.0,280000.0
2,That's Not Cheese,1/26/2016,B&W,Drama,German,Germany,Not Rated,Justin Groove,Anne Spandex,291.0,938.0,12.0,11501.0,8.3,215.0,145.0,3450000.0,650000.0
3,Sugar Rush,11/11/2016,Color,Comedy,English,USA,PG,Karen Trout,Humberto Guava,431.0,673.0,22.0,18363.0,6.3,433.0,100.0,2808000.0,379000.0
4,Why is Grandma Laughing?,8/29/2016,Color,Mystery,English,USA,PG-13,Yulia Velasquez,Purd Haply,86.0,623.0,1.0,4771.0,7.7,110.0,89.0,1700000.0,439000.0
5,Luke Warm Soup,4/15/2016,Color,Horror,English,USA,R,Skeeter McGavin,Nick Winkle,167.0,659.0,20.0,14580.0,9.3,209.0,81.0,3000000.0,609000.0
6,Clown Parade III,6/1/2016,Color,Comedy,English,USA,PG,Stan Pancake,Todd Waffle,444.0,900.0,11.0,15977.0,4.2,172.0,112.0,3250000.0,500000.0
7,Gene's Genes,8/11/2016,Color,Sci-Fi,Spanish,Spain,PG,Randy Killnose,August Clementine,406.0,879.0,6.0,10949.0,6.6,123.0,121.0,1980000.0,250000.0

In [123]:
# FETCH ALL COLOR MOVIES
color_movies = df['Color/B&W'] == 'Color'
df[color_movies]

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
0,Adventure Squirrels,2/15/2016,Color,Drama,French,France,G,Jim Tickle,Lloyd Christmas,314.0,798.0,25.0,1310.0,6.7,54.0,93.0,1200000.0,100000.0
1,Too Many Balloons,9/15/2016,Color,Crime,English,USA,R,Phil Stump,Alan Creamsicle,309.0,520.0,26.0,10805.0,4.2,192.0,110.0,3000000.0,280000.0
3,Sugar Rush,11/11/2016,Color,Comedy,English,USA,PG,Karen Trout,Humberto Guava,431.0,673.0,22.0,18363.0,6.3,433.0,100.0,2808000.0,379000.0
4,Why is Grandma Laughing?,8/29/2016,Color,Mystery,English,USA,PG-13,Yulia Velasquez,Purd Haply,86.0,623.0,1.0,4771.0,7.7,110.0,89.0,1700000.0,439000.0
5,Luke Warm Soup,4/15/2016,Color,Horror,English,USA,R,Skeeter McGavin,Nick Winkle,167.0,659.0,20.0,14580.0,9.3,209.0,81.0,3000000.0,609000.0
6,Clown Parade III,6/1/2016,Color,Comedy,English,USA,PG,Stan Pancake,Todd Waffle,444.0,900.0,11.0,15977.0,4.2,172.0,112.0,3250000.0,500000.0
7,Gene's Genes,8/11/2016,Color,Sci-Fi,Spanish,Spain,PG,Randy Killnose,August Clementine,406.0,879.0,6.0,10949.0,6.6,123.0,121.0,1980000.0,250000.0

In [163]:
i = df['Color/B&W'] == 'B&W'
df[i]

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
2,That's Not Cheese,1/26/2016,B&W,Drama,German,Germany,Not Rated,Justin Groove,Anne Spandex,291.0,938.0,12.0,11501.0,8.3,215.0,145.0,3450000.0,650000.0

In [179]:
a = df["Genre"] == "Comedy"
b = df["Release Date"] != "6/1/2016"
c = df["Gross Revenue"] > 2000000.0

In [180]:
df[a&b&c]

,Title,Release Date,Color/B&W,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score (1-10),Total Reviews,Duration (min),Gross Revenue,Budget
3,Sugar Rush,11/11/2016,Color,Comedy,English,USA,PG,Karen Trout,Humberto Guava,431.0,673.0,22.0,18363.0,6.3,433.0,100.0,2808000.0,379000.0